orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

version: 2.1

workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: dind-builder
          registry-url: us.gcr.io
